/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrincipleCardsRouteImport } from './routes/principle-cards'
import { Route as SeatCardsRouteImport } from './routes/seat-cards'
import { Route as SituationCardsRouteImport } from './routes/situation-cards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipleCardsRoute = PrincipleCardsRouteImport.update({
  id: '/principle-cards',
  path: '/principle-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const SeatCardsRoute = SeatCardsRouteImport.update({
  id: '/seat-cards',
  path: '/seat-cards',
  getParentRoute: () => rootRouteImport,
} as any)
const SituationCardsRoute = SituationCardsRouteImport.update({
  id: '/situation-cards',
  path: '/situation-cards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/principle-cards': typeof PrincipleCardsRoute
  '/seat-cards': typeof SeatCardsRoute
  '/situation-cards': typeof SituationCardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/principle-cards': typeof PrincipleCardsRoute
  '/seat-cards': typeof SeatCardsRoute
  '/situation-cards': typeof SituationCardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/principle-cards': typeof PrincipleCardsRoute
  '/seat-cards': typeof SeatCardsRoute
  '/situation-cards': typeof SituationCardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/principle-cards' | '/seat-cards' | '/situation-cards'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/principle-cards' | '/seat-cards' | '/situation-cards'
  id: '__root__' | '/' | '/principle-cards' | '/seat-cards' | '/situation-cards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrincipleCardsRoute: typeof PrincipleCardsRoute
  SeatCardsRoute: typeof SeatCardsRoute
  SituationCardsRoute: typeof SituationCardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principle-cards': {
      id: '/principle-cards'
      path: '/principle-cards'
      fullPath: '/principle-cards'
      preLoaderRoute: typeof PrincipleCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seat-cards': {
      id: '/seat-cards'
      path: '/seat-cards'
      fullPath: '/seat-cards'
      preLoaderRoute: typeof SeatCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situation-cards': {
      id: '/situation-cards'
      path: '/situation-cards'
      fullPath: '/situation-cards'
      preLoaderRoute: typeof SituationCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrincipleCardsRoute: PrincipleCardsRoute,
  SeatCardsRoute: SeatCardsRoute,
  SituationCardsRoute: SituationCardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
